name: Pull Request - Report

on:
  # When manually triggered
  workflow_dispatch:

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        uses: actions/github-script@v7
        with:
          script: |
            // Get all pull requests
            const pull_requests = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              sort: "created",
              direction: "asc",
            });
            console.log("Pull requests:", JSON.stringify(pull_requests, null, 2));
