name: Pull Request

on:
  pull_request_target:

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        uses: actions/github-script@v7
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string

      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
