name: Pull Request

on:
  # When a pull request is opened, synchronized or reopened
  pull_request_target:

  # When a pull request review is submitted, edited or dismissed
  pull_request_review:

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            const pullRequest = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }},
            });
            console.log("Pull request:", pullRequest);
            
            const reviews = await github.paginate(github.rest.pulls.listReviews, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }},
            });
            console.log("Reviews:", reviews);
            
            const reviewsPerUser = new Map();
            for (const review of reviews) {
              const previousReviews = reviewsPerUser.get(review.user.id) ?? [];
              reviewsPerUser.set(review.user.id, [...previousReviews, review]);
            }
            console.log("Reviews per user:", reviewsPerUser);
