name: Pull Request - Report

on:
  # When manually triggered
  workflow_dispatch:

env:
  PENDING_REVIEW_LABEL: "Review: Pending"
  CHANGES_REQUESTED_LABEL: "Review: Changes requested"
  APPROVED_LABEL: "Review: Approved"

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        uses: actions/github-script@v7
        with:
          script: |
            // Get all pull requests
            const pull_requests = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              sort: "created",
              direction: "asc",
            });
            
            // Find pending pull requests
            const pending_pull_requests = pull_requests.filter((pull_request) => pull_request.labels.some((label) => label.name === process.env.PENDING_REVIEW_LABEL));
            console.log("Pending pull requests:", pending_pull_requests);
            
            // Find changes requested pull requests
            const changes_requested_pull_requests = pull_requests.filter((pull_request) => pull_request.labels.some((label) => label.name === process.env.CHANGES_REQUESTED_LABEL));
            console.log("Changes requested pull requests:", changes_requested_pull_requests);
        
            // Find approved pull requests
            const approved_pull_requests = pull_requests.filter((pull_request) => pull_request.labels.some((label) => label.name === process.env.APPROVED_LABEL));
            console.log("Approved pull requests:", approved_pull_requests);
